EventaDors.WebApplication/Controllers/ContentController.cs
using Microsoft.AspNetCore.Mvc;

namespace EventaDors.WebApplication.Controllers
{
    public class ContentController : Controller
    {
        public IActionResult Features()
        {
            return View();
        } 
        
        public IActionResult AboutUs()
        {
            return View();
        }

        public IActionResult Home()
        {
            return View();
        }
    }

    public class VenuesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        } 
    }
}

EventaDors.WebApplication/Controllers/QuoteTemplateController.cs
using System;
using System.Linq;
using EventaDors.DataManagement;
using EventaDors.Entities.Classes;
using EventaDors.WebApplication.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EventaDors.WebApplication.Controllers
{
    public class QuoteTemplateController : Controller
    {
        private readonly Wrapper _wrapper;

        public QuoteTemplateController(Wrapper wrapper)
        {
            _wrapper = wrapper;
        }
        // GET
        public IActionResult Index()
        {
            var id = Request.Query["id"];

            QuoteTemplateEvent ev = _wrapper.GetQuoteTemplateEvent(int.Parse(id));
            
            return View(ev);
        }

        [HttpGet]
        public IActionResult ChosenTemplate(int Id)
        {
            var quoteTemplate = _wrapper.GetQuoteTemplates(Id);

            foreach (var evt in quoteTemplate.First().Events)
            {
                var elements = _wrapper.GetQuoteTemplateEvent(evt.Id);
                foreach (var element in elements.TemplateElements)
                {
                    evt.TemplateElements.Add(element);
                }
            }
            
            return View(quoteTemplate.First());
        }

        [HttpPost]
        [HttpGet]
        public IActionResult ProcessTemplate(QuoteTemplate quoteTemplate)
        {
            if (HttpContext.Session.Keys.All(x => x != Statics.EmailTempData))
            {
                return RedirectToAction("Index", "Registration");
            }
            
            QuoteRequest quoteRequest = null;
            
            if(!Request.Query.ContainsKey("quoteIdIdentity"))
            {
                string email = (HttpContext.Session.Keys.Contains(Statics.EmailTempData)
                    ? HttpContext.Session.GetString(Statics.EmailTempData)
                    : String.Empty);
                User user = _wrapper.CreateUser(email);
                Journey journey = _wrapper.GetJourney(email);

                var templateId = 0;
                if (Request.Method == "POST")
                {
                    int attendance = int.Parse(Request.Form["Attendees"]);
                    templateId = int.Parse(Request.Form["TemplateId"]);
                    quoteRequest =
                        _wrapper.CreateRequestFromTemplate(templateId, user.Id, attendance, journey.EventDate);
                    return View(quoteRequest);
                }

                if (!journey.QuoteIdIdentity.HasValue)
                {
                    if (journey.Completed.HasValue)
                    {
                        if(!HttpContext.Session.Keys.Contains(Statics.EmailTempData))
                            HttpContext.Session.SetString(Statics.EmailTempData, journey.Email);
                        return RedirectToAction("Step3", "Registration");
                    }
                }
                else
                {
                    templateId = journey.QuoteIdIdentity.Value;
                
                    if (Request.Method == "GET")
                    {
                        quoteRequest = _wrapper.LoadQuoteRequest(templateId);
                    }
                }
            }
            else
            {
                int id = int.Parse(Request.Query["quoteIdIdentity"]);
                quoteRequest = _wrapper.LoadQuoteRequest(id);
            }

            if (Request.Query.ContainsKey(Statics.ProcessingStatus))
            {
                quoteRequest.ProcessingResult = Enum.Parse<ProcessingResult>(Request.Query[Statics.ProcessingStatus]);
                quoteRequest.ProcessingMessage = Request.Query[Statics.ProcessingMessage];
            }
            
            return View(quoteRequest);
        }

        public IActionResult ProcessEventUpdates()
        {
            return View();
        }

        public IActionResult EditEventDetails()
        {
            var quoteEvent = new QuoteRequestEvent();
            int eventId = int.Parse(Request.Query["eventId"]);
            int quoteId = int.Parse(Request.Query["quoteId"]);
            return View(quoteEvent);
        }

        [HttpPost]
        public IActionResult UpdateWedding(QuoteRequest request)
        {
            int id = int.Parse(Request.Form["QuoteIdIdentity"]);
            return RedirectToAction("ProcessTemplate", "QuoteTemplate", new
            {
                quoteIdIdentity = id,
                status = ProcessingResult.Success,
                message = "Wedding event saved successfully"
            });
        }
    }
}

EventaDors.WebApplication/Views/QuoteTemplate/ChosenTemplate.cshtml
@using EventaDors.Entities.Classes
@model EventaDors.Entities.Classes.QuoteTemplate

@{
    Layout = "_NewLayout";;
}

<!DOCTYPE html>
<div class="container">
    @if (Model != null)
        {
            <h2>Chosen Template is [@Model.Name]</h2>
        }
    <p>If there is an event you wish to exclude from your wedding simply uncheck the box next to the item.</p>
    <p>If an event is excluded then so will all its contained elements.</p>
    <p>One or more individual elements an also be excluded.</p>
    <p>These items can also be added and excluded later if required so feel free to simply take them all at this stage.</p>
    <form asp-action="ProcessTemplate">
        <table class="table-bordered table-striped" style="width:100%">
            <tr></tr><tr><input style="background: rgb(144,109,154);color: rgb(252,209,91); width: 100%" class="btn btn-light action-button" type="submit" value="Generate" class="btn btn-info w-100"/></tr>
            <tr><td></td>
                <td>Approximate Attendance:</td>
                <td>
                    <input type="number" asp-for="Attendees" id="Attendees" name="Attendees" value="50"/>
                    <span asp-validation-for="Attendees" class="text-danger"></span>
                </td>
            </tr>
            <tr><td colspan="3"></td>
            @foreach (var evt in Model.Events)
            {
                <tr><td><input checked="true" type="checkbox" value="true" name="Event_@evt.Id" id="Event_@evt.Id"/></td>
                    <td>
                        <h5>@evt.Event.Name</h5></td><td></td></tr>
                @if (evt.TemplateElements.Count > 0)
                {
                    foreach (QuoteElement quoteElement in evt.TemplateElements)
                    {
                        <tr><td></td><td></td>
                            <td>
                                <table class="table-bordered table-striped" style="width:100%">
                                    <tr>

                                        <td>
                                            <input checked="true" type="checkbox" id="Event_@evt.Id|Element_@quoteElement.Id" name="Event_@evt.Id|Element_@quoteElement.Id"/>
                                            <label for="@quoteElement.Id">@quoteElement.Name (@quoteElement.Id)</label>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    }
                }
            }
        </table>
        <input type="hidden" name="TemplateId" value="@Model.Id"/>
    </form>
    <a href="javascript:history.back()"><< Back</a>
</div>

EventaDors.WebApplication/Views/QuoteTemplate/EditEventDetails.cshtml
@model EventaDors.Entities.Classes.QuoteRequestEvent

@{
    ViewBag.Title = "title";
    Layout = "_NewLayout";
}
<div class="container">
    <h2>Event Details</h2>
    <A href="javascript:history.back()" class="form-control" >&lt; Back</A> 
</div>

EventaDors.WebApplication/Views/QuoteTemplate/Index.cshtml
@model EventaDors.Entities.Classes.QuoteTemplateEvent

@{
    Layout = "_NewLayout";;
}

<div class="container">
    <a href="javascript:history.back()" class="form-control" >&lt; Back</a>
    <table class="table-bordered table-striped" style="width:100%">
        <thead>
        <tr>
            <td colspan="3">
                <h3>@Model.Event.Name</h3></td></tr>
        </thead>
        <tbody>
        <tr><td colspan="3"><span>@Html.Raw(Model.Event.Notes.Trim())</span></td></tr>
        <tr><td colspan="3"></tr>
        <tr><td colspan="3"><b>Elements</b></td></tr>
        @foreach (var element in Model.TemplateElements)
        {
            <tr><td align="right">-</td><td>@element.Name</td><td>@element.Notes</td></tr>
        }
        </tbody>
    </table>
</div>

EventaDors.WebApplication/Views/QuoteTemplate/ProcessEventUpdates.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_NewLayout";
}

<div class="container"><h2>title</h2></div>

EventaDors.WebApplication/Views/QuoteTemplate/ProcessTemplate - Copy.cshtml
@using EventaDors.Entities.Classes
@model EventaDors.Entities.Classes.QuoteRequest

@{
    ViewBag.Title = "title";
    Layout = "_NewLayout";
}


<div class="container">
    <h2>@Model.Name</h2>
    <form asp-action="ProcessEventUpdates">
        <p><b>Note:</b> Adjusting the main event due date will recalulate all dependent dates unless they are specifically <a href="javascript:alert('Link to help')"> protected from moving.</a></p>
        <input type="hidden" asp-for="QuoteIdIdentity"/>
        <table class="table-bordered table-striped" style="width:100%">
            <tr>
                <td>Main Event Name:</td>
                <td><input type="text" asp-for="Name" class="form-control"/></td>
                <td><span asp-validation-for="Name" class="text-danger"></span></td>
            </tr>
            <tr>
                <td valign="top">Notes:</td>
                <td><textarea rows="4" cols="10" style="width: 100%" asp-for="Notes" class="form-control">@Model.Notes</textarea></td>
                <td></td>
            </tr>
            <tr>
                <td>Attendees (Approx):</td>
                <td><input type="number" asp-for="Attendees" class="form-control"/></td>
                <td><span asp-validation-for="Attendees" class="text-danger"></span></td>
            </tr>
            <tr>
                <td>Main Date:</td>
                <td><input type="date" asp-for="DueDate" class="form-control"/></td>
                <td><span asp-validation-for="DueDate" class="text-danger"></span></td>
            </tr>
            <tr>
                <td colspan="3">
                    <h3>Events</h3></td></tr>
            @foreach (var evt in Model.Events)
            {
                <tr>
                    <td valign="middle">
                        <a href="javascript:window.alert('@GetHelpMessage(evt, nameof(evt.Name))')"><img width="15px" height="15px" src="~/images/help.png" alt="@GetHelpMessage(evt, nameof(evt.LeadWeeks))"></a> Event Name:
                    </td>
                    <td><input asp-for="@evt.Name" class="form-control"></td>
                    <td></td>
                </tr>
                <tr>
                    <td valign="middle">
                        <a href="javascript:window.alert('@GetHelpMessage(evt, nameof(evt.EventDate))')"><img width="15px" height="15px" src="~/images/help.png" alt="@GetHelpMessage(evt, nameof(evt.LeadWeeks))"></a> Event Date:
                    </td>
                    <td><input type="date" asp-for="@evt.EventDate" class="form-control"></td>
                    <td></td>
                </tr>
                <tr>
                    <td valign="middle">
                        <a href="javascript:window.alert('@GetHelpMessage(evt, nameof(evt.LeadWeeks))')"><img width="15px" height="15px" src="~/images/help.png" alt="@GetHelpMessage(evt, nameof(evt.LeadWeeks))"></a> Lead Weeks:
                    </td>
                    <td><input type="number" asp-for="@evt.LeadWeeks" class="form-control"></td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td valign="middle">
                        <a href="javascript:window.alert('@GetHelpMessage(evt, nameof(evt.Venue))')"><img width="15px" height="15px" src="~/images/help.png" alt="@GetHelpMessage(evt, nameof(evt.LeadWeeks))"></a> Venue:
                    </td>
                    <td><b>@GetVenueName(evt.Venue)</b></td>
                    <td></td>
                </tr>
                <tr><td colspan="3" align="right"><a class="btn btn-light action-button" style="background: rgb(144,109,154);color: rgb(252,209,91);" asp-action="EditEventDetails" asp-route-eventId="@evt.Id" asp-route-quoteId="@Model.QuoteIdIdentity">Edit Event...</a> </td></tr>
            }
        </table>
    </form>
</div>
@functions
{
    string GetVenueName(Venue venue)
    {
        string ret = "(Not Set)";
        if (venue != null)
            ret = venue.ToString();
        return ret;
    }

    string GetHelpMessage(CreatedModifiedBase obj, string name)
    {
        return obj.HelpMessages[name];
    }
}

EventaDors.WebApplication/Views/QuoteTemplate/ProcessTemplate.cshtml
@using EventaDors.Entities.Classes
@model EventaDors.Entities.Classes.QuoteRequest

@{
    ViewBag.Title = "title";
    Layout = "_NewLayout";
}


<div class="container">
    @if (Model.ProcessingResult == ProcessingResult.Success)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>@Model.ProcessingResult.ToString()</strong> @Model.ProcessingMessage
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <form asp-action="UpdateWedding" asp-controller="QuoteTemplate">
        <div class="container" style="align: right">
            <a style="background: rgb(144,109,154);color: rgb(252,209,91);" class="btn btn-light action-button" href="javascript:history.back()" class="form-control">&lt; Back</a>
            <input type="submit" class="btn btn-light action-button" style="background: rgb(144,109,154);color: rgb(252,209,91);" value="Save Changes">
        </div>
        <p></p>
        <div class="row">
            <h4><i class="fa fa-heart"></i> @Model.Name</h4>
        </div>
        <input name="QuoteIdIdentity" type="hidden" value="@Model.QuoteIdIdentity"/>
        <div class="form-row">
            <div class="col">
                <div class="form-floating">
                    <input type="text" class="form-control" id="Wedding_Name" name="Wedding_Name" asp-for="Name">
                    <label for="Wedding_Name">Wedding Name</label>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col">
                <div class="form-floating">
                    <input type="number" class="form-control" id="Wedding_Attendees" name="Wedding_Attendees" asp-for="Attendees">
                    <label for="Wedding_Attendees">Attendees</label>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col">
                <div class="form-floating">
                    <textarea name="Wedding_Notes" class="form-control" id="Wedding_Notes">@Model.Notes</textarea>
                    <label for="Wedding_Notes">Notes</label>
                </div>
            </div>
        </div>
        <div role="tablist" id="accordion-0">
            @{
                int i = 1;
                int item = 0;
                int elementCount = 0;
            }
            @foreach (var evt in Model.Events)
            {
                elementCount = 0;

                    <div class="card">
                        <div class="card-header" role="tab">
                            <h5 class="mb-0"><a data-toggle="collapse" aria-expanded="true" aria-controls="accordion-0 .item-@item" href="#accordion-0 .item-@item"><i class="fa fa-tags"></i> @evt.Name</a></h5>
                        </div>
                    <div class="collapse item-@item" role="tabpanel" data-parent="#accordion-0">
                        <div class="card-body">
                            <div class="form-row">
                                <div class="col">
                                    <div class="form-floating">
                                        <input name="event.Name.@evt.QuoteRequestEventId" class="form-control" id="event.Name.@evt.QuoteRequestEventId" asp-for="@evt.Name">
                                        <label for="event.Name.@evt.QuoteRequestEventId">Event Name</label>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-floating">
                                        <input name="event.Notes.@evt.QuoteRequestEventId" class="form-control" id="event.Notes.@evt.QuoteRequestEventId" asp-for="@evt.Notes">
                                        <label for="event.Notes.@evt.QuoteRequestEventId">Event Notes</label>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-floating">
                                        <input type="date" name="event.EventDate.@evt.QuoteRequestEventId" class="form-control" id="event.EventDate.@evt.QuoteRequestEventId" asp-for="@evt.EventDate">
                                        <label for="event.EventDate.@evt.QuoteRequestEventId">Event Date/Time</label>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-floating">
                                        <input name="event.LeadWeeks.@evt.QuoteRequestEventId" class="form-control" id="event.LeadWeeks.@evt.QuoteRequestEventId" asp-for="@evt.LeadWeeks">
                                        <label for="event.LeadWeeks.@evt.QuoteRequestEventId">Lead Weeks</label>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-floating">
                                        <input list="datalistOptions" type="text" name="event.Venue.@evt.QuoteRequestEventId" placeholder="No venues set up for this event"
                                               class="form-control" id="event.Venue.@evt.QuoteRequestEventId" value="@GetVenueName(evt.Venue)">
                                        <label for="event.Venue.@evt.QuoteRequestEventId">Venue (Must be set up first)</label>
                                        <datalist id="datalistOptions">
                                            <option value="The Basement, Leicester, LE1 6HH"/>
                                            <option value="St Andrew's Church, Leicester, LE4"/>
                                            <option value="Quorn Country Hotel, Leicester, LE12 8BB"/>
                                            <option value="Bride's Home, Leicester, LE3 4ER"/>
                                            <option value="Grooms's Home, Leicester, LE3 6UR"/>
                                            <option value="(none)"/>
                                        </datalist>
                                    </div>
                                </div>
                                <div class="col" align="right"><a asp-action="Index" asp-controller="Venues">Manage Venues</a></div>
                            </div>
                            @foreach (var element in evt.Elements)
                            {
                                elementCount++;
                                <div role="tablist" id="accordion-@i">
                                    <div class="card">
                                        <div class="card-header" role="tab">
                                            <h5 class="mb-0"><a data-toggle="collapse" aria-expanded="true" aria-controls="accordion-@i .item-@elementCount" href="#accordion-@i .item-@elementCount"><i class="far fa-list-alt"></i> @element.Name</a></h5>
                                        </div>
                                        <div class="collapse item-@elementCount" role="tabpanel" data-parent="#accordion-@i">
                                            <div class="card-body">
                                                <div class="form-row">
                                                     <div class="col">
                                                        <div class="form-floating">
                                                            <input name="element.Name.@element.QuoteRequestElementId" class="form-control" id="element.Name.@element.QuoteRequestElementId" asp-for="@element.Name">
                                                            <label for="element.Name.@element.QuoteRequestElementId">Element Name</label>
                                                        </div>
                                                     </div> 
                                                    <div class="col">
                                                        <div class="form-floating">
                                                            <input name="element.Notes.@element.QuoteRequestElementId" class="form-control" id="element.Notes.@element.QuoteRequestElementId" asp-for="@element.Notes">
                                                            <label for="element.Notes.@element.QuoteRequestElementId">Notes</label>
                                                        </div>
                                                     </div> 
                                                    <div class="col">
                                                        <div class="form-floating">
                                                            <input name="element.Budget.@element.QuoteRequestElementId" class="form-control" id="element.Budget.@element.QuoteRequestElementId" type="number" asp-for="@element.Budget">
                                                            <label for="element.Budget.@element.QuoteRequestElementId">Budget</label>
                                                        </div>
                                                    </div> 
                                                    <div class="col">
                                                        <div class="form-floating">
                                                            <input name="element.DueDate.@element.QuoteRequestElementId" class="form-control" id="element.DueDate.@element.QuoteRequestElementId" type="date" asp-for="@element.DueDate">
                                                            <label for="element.DueDate.@element.QuoteRequestElementId">Due Date</label>
                                                        </div>
                                                    </div> 
                                                    <div class="col">
                                                        <div class="form-floating">
                                                            <input name="element.Quantity.@element.QuoteRequestElementId" class="form-control" id="element.Quantity.@element.QuoteRequestElementId" type="number" asp-for="@element.Quantity">
                                                            <label for="element.Quantity.@element.QuoteRequestElementId">Quantity</label>
                                                        </div>
                                                    </div> 
                                                    <div class="col">
                                                        <div class="form-floating">
                                                            <input name="element.LeadWeeks.@element.QuoteRequestElementId" class="form-control" id="element.LeadWeeks.@element.QuoteRequestElementId" type="number" asp-for="@element.LeadWeeks">
                                                            <label for="element.LeadWeeks.@element.QuoteRequestElementId">Lead Weeks</label>
                                                        </div>
                                                    </div> 
                                                    <div class="form-row" align="right">
                                                        <input type="checkbox" name="element.Completed.@element.QuoteRequestElementId" id="element.Completed.@element.QuoteRequestElementId" asp-for="@element.Completed"/>
                                                        <label for="element.Completed.@element.QuoteRequestElementId">Completed</label>
                                                        <input type="checkbox" name="element.Exclude.@element.QuoteRequestElementId" id="element.Exclude.@element.QuoteRequestElementId" asp-for="@element.Exclude"/>
                                                        <label for="element.Exclude.@element.QuoteRequestElementId">Exclude this element</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                item++;
                i++;
            }
        </div>
    </form>
</div>
@functions
{
    string GetVenueName(Venue venue)
    {
        string ret = "(none)";
        if (venue != null)
            ret = venue.ToString();
        return ret;
    }

    string GetHelpMessage(CreatedModifiedBase obj, string name)
    {
        return obj.HelpMessages[name];
    }
}

EventaDors.WebApplication/Views/QuoteTemplate/UpdateWedding.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_NewLayout";
}

<h2>title</h2>