EventaDors.WebApplication/Controllers/AboutYouController.cs
using System;
using System.Linq;
using EventaDors.Entities.Classes;
using EventaDors.WebApplication.Helpers;
using EventaDors.WebApplication.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;

namespace EventaDors.WebApplication.Controllers
{
    public class AboutYouController : Controller
    {
        public IActionResult Index(Journey journey)
        {
            if (journey.IsEmpty)
            {

                journey.Title = (HttpContext.Session.Keys.Contains(Statics.Title) ? HttpContext.Session.GetString(Statics.Title) : string.Empty) ;
                journey.FirstName = (HttpContext.Session.Keys.Contains(Statics.Title) ? HttpContext.Session.GetString(Statics.FirstName) : String.Empty);
                journey.FirstName = (HttpContext.Session.Keys.Contains(Statics.Surname) ? HttpContext.Session.GetString(Statics.Surname) : String.Empty);
                journey.FirstName = (HttpContext.Session.Keys.Contains(Statics.PostalCode) ? HttpContext.Session.GetString(Statics.PostalCode) : String.Empty);
                journey.FirstName = (HttpContext.Session.Keys.Contains(Statics.ContactNumber) ? HttpContext.Session.GetString(Statics.ContactNumber) : String.Empty);
                journey.FirstName = (HttpContext.Session.Keys.Contains(Statics.PartnerEmail) ? HttpContext.Session.GetString(Statics.PartnerEmail) : String.Empty);
                journey.FirstName = (HttpContext.Session.Keys.Contains(Statics.EventDate) ? HttpContext.Session.GetString(Statics.EventDate) : String.Empty);
            }
            
            HttpContext.Session.SetString(Statics.Title, journey.Title);
            HttpContext.Session.SetString(Statics.FirstName, journey.FirstName);
            HttpContext.Session.SetString(Statics.Surname, journey.Surname);
            HttpContext.Session.SetString(Statics.PostalCode, journey.PostalCode);
            HttpContext.Session.SetString(Statics.ContactNumber, journey.ContactNumber);
            HttpContext.Session.SetString(Statics.PartnerEmail, journey.PartnerEmail);
            HttpContext.Session.SetString(Statics.EventDate, journey.EventDate.Value.ToShortDateString());

            if (string.IsNullOrEmpty(journey.CurrentPage))
            {
                journey.CurrentPage = "Story";
                return View(journey);
            }

            if (journey.CurrentPage == "Story")
            {
                journey.CurrentPage = null;
                return RedirectToAction("ContinueRegistration", "Register", journey);
            }

            return null;
        }
    }
}

EventaDors.WebApplication/Controllers/LoginController.cs
using EventaDors.DataManagement;
using EventaDors.Entities.Classes;
using EventaDors.WebApplication.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EventaDors.WebApplication.Controllers
{
    public class LoginController : Controller
    {
        private readonly Wrapper _wrapper;

        public LoginController(Wrapper wrapper)
        {
            _wrapper = wrapper;
        }

        [HttpPost]
        public IActionResult ProcessLogin(User loginUser)
        {
            if (_wrapper.LoginUser(loginUser))
            {
                loginUser = _wrapper.CreateUser(loginUser.Id);
                HttpContext.Session.SetString(Statics.LogonUserKey, loginUser.Id.ToString());
                return RedirectToAction("Index", "StatusScreen", loginUser.Id);
            }

            return new ForbidResult();
        }
    }
}

EventaDors.WebApplication/Controllers/RegisterController.cs
using System;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using EventaDors.DataManagement;
using EventaDors.Entities.Classes;
using EventaDors.WebApplication.Helpers;
using EventaDors.WebApplication.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EventaDors.WebApplication.Controllers
{
    public class RegisterController : Controller
    {
        private readonly Wrapper _wrapper;

        public RegisterController(Wrapper wrapper)
        {
            _wrapper = wrapper;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProcessRegistration(Journey journey)
        {
            if (!journey.EventDate.HasValue)
            {
                _wrapper.RegisterUser(journey.User);
            }

            return View("ContinueRegistration", journey);
        } 
        public IActionResult ContinueRegistration(string userId, Journey journey)
        {
            if (string.IsNullOrEmpty(userId))
                userId = HttpContext.Session.GetString(Statics.LogonUserKey);
            var user = _wrapper.CreateUser(long.Parse(userId));
            HttpContext.Session.SetString(Statics.UserIdKey, userId);
            return ProcessRegistration(new Journey
            {
                User = user,
                ContactNumber = (HttpContext.Session.Keys.Contains(Statics.ContactNumber) ? HttpContext.Session.GetString(Statics.ContactNumber) : String.Empty),
                FirstName = (HttpContext.Session.Keys.Contains(Statics.FirstName) ? HttpContext.Session.GetString(Statics.FirstName) : String.Empty),
                Surname = (HttpContext.Session.Keys.Contains(Statics.Surname) ? HttpContext.Session.GetString(Statics.Surname) : String.Empty),
                PartnerEmail = (HttpContext.Session.Keys.Contains(Statics.PartnerEmail) ? HttpContext.Session.GetString(Statics.PartnerEmail) : String.Empty),
                PostalCode = (HttpContext.Session.Keys.Contains(Statics.PostalCode) ? HttpContext.Session.GetString(Statics.PostalCode) : String.Empty),
                EventDate = GetEventDate()
            });
        }

        private DateTime GetEventDate()
        {
            var dateString = (HttpContext.Session.Keys.Contains(Statics.EventDate) ? HttpContext.Session.GetString(Statics.EventDate) : String.Empty);
            if(!string.IsNullOrEmpty(dateString))
                return DateTime.Parse(dateString);
            return DateTime.Today.AddDays(365);
        }
    }
}

EventaDors.WebApplication/Views/Register/ContinueRegistration.cshtml
@model EventaDors.Entities.Classes.Journey

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Start Your Journey</h2>
<p>To start your journey to your special day we need to gather some basic information from you so we can maximise the help we can give you.</p>
<p>Please answer the following question as accurately as you can.</p>
<h4>When is the special day?</h4>
<form method="post" asp-controller="AboutYou" asp-action="Index">
    <table style="width: 100%">
        <thead>
        <tr>
            <td></td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td width="100%">
                <input asp-for="EventDate">
            </td>
        </tr>
        <tr><hr></hr></tr>
        <tr>
            <td><input type="submit" class="btn btn-info w-100" value="Next >>" /></td>
        </tr>
        </tbody>
    </table>
</form>

EventaDors.WebApplication/Views/Register/Index.cshtml
@model EventaDors.Entities.Classes.Journey

@{
    Layout = "_Layout";
}

<h2>Register with @Statics.ApplicationName</h2>
<h3>Register</h3>

<p>Please enter your email address and choose a password in the fields below and click Register</p>
<p>If you are already a member <a asp-controller="Login" asp-action="Index">click here</a> to login.</p>
<hr>
<form method="post" asp-controller="Register" asp-action="ProcessRegistration">
    <table style="width: 100%" >
        <tr>
            <td>Email Address:</td>
            <td><input id="email" asp-for="User.PrimaryEmail" style="width: 100%" type="text" class="form-control"/>
        </tr>
        <tr>
            <td>Password:</td>
            <td><input id="password" asp-for="User.CurrentPassword" style="width: 100%" type="password" class="form-control"/></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" class="btn btn-info w-100" value="Register" /></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
        </tr>
    </table>
    <hr>
    <p>You will receive a confirmation email to the address supplied. Please click on the link to confirm your membership of @Statics.ApplicationName</p>
</form>

EventaDors.WebApplication/Views/Register/ProcessRegistration.cshtml
@model EventaDors.Entities.Classes.Journey

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Start Your Journey</h2>
<p>To start your journey to your special day we need to gather some basic information from you so we can maximise the help we can give you.</p>
<p>Please answer the following question as accurately as you can.</p>
<h4>When is the special day?</h4>
<form method="post" asp-controller="AboutYou" asp-action="Index">
    <table style="width: 100%">
        <thead>
        <tr>
            <td></td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td width="100%">
                <input asp-for="EventDate">
            </td>
        </tr>
        <tr><hr></hr></tr>
        <tr>
            <td><input type="submit" class="btn btn-info w-100" value="Next >>" /></td>
        </tr>
        </tbody>
    </table>
</form>